import type { Metadata } from "next";
import "./styles/globals.css";
import localFont from "next/font/local";

const neueHaas = localFont({
  src: "../public/fonts/NeueHaasDisplayRoman.woff2",
  weight: "400",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={neueHaas.className}>{children}</body>
    </html>
  );
}
